/**
 * Amanah AI — Halal Ingredient Dictionary
 * Classified strictly per JAKIM (Jabatan Kemajuan Islam Malaysia) standards.
 * Sources: JAKIM Halal Hub, MUI Fatwa, IFANCA, Codex Alimentarius.
 *
 * status:
 *   "halal"    — permissible; no animal-derived components or from plant/mineral/synthetic origin
 *   "haram"    — prohibited; pork-derived, insect-derived, or from non-halal slaughter
 *   "doubtful" — mashbooh; source ambiguous or depends on supplier declaration
 */

export interface HalalEntry {
  name: string;
  aliases?: string[];
  status: "halal" | "haram" | "doubtful";
  category: string;
  description: string;
  jakimRef?: string;
  /** Recommended halal-compliant alternative ingredient */
  halal_alternative?: string;
  /** Mock trusted suppliers that provide the halal alternative */
  trusted_suppliers?: string[];
}

export const HALAL_DICTIONARY: HalalEntry[] = [

  // ── COLORANTS ──────────────────────────────────────────────────────────────

  {
    name: "E100 — Curcumin",
    aliases: ["Turmeric yellow", "CI Natural Yellow 3"],
    status: "halal",
    category: "Colorant",
    description: "Natural yellow pigment extracted from turmeric root (Curcuma longa). Purely plant-derived. Widely accepted by JAKIM.",
    jakimRef: "JAKIM-COL-001",
  },
  {
    name: "E101 — Riboflavin",
    aliases: ["Vitamin B2", "Lactoflavin"],
    status: "halal",
    category: "Colorant",
    description: "Yellow dye produced by microbial fermentation or synthetic synthesis. No animal components. Halal certified by JAKIM.",
    jakimRef: "JAKIM-COL-002",
  },
  {
    name: "E102 — Tartrazine",
    aliases: ["FD&C Yellow 5", "CI Food Yellow 4"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic azo dye. Produced entirely from petrochemical sources. No animal-derived inputs. Halal.",
    jakimRef: "JAKIM-COL-003",
  },
  {
    name: "E110 — Sunset Yellow FCF",
    aliases: ["FD&C Yellow 6", "Orange Yellow S"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic azo dye derived from petroleum. No animal components. Accepted under JAKIM halal guidelines.",
    jakimRef: "JAKIM-COL-004",
  },
  {
    name: "E120 — Carmine",
    aliases: ["Cochineal", "Natural Red 4", "CI 75470"],
    status: "haram",
    category: "Colorant",
    description: "Red dye extracted from dried female cochineal insects (Dactylopius coccus). Insect-derived — strictly HARAM under JAKIM fatwa. Found in juices, yoghurts, confectionery.",
    jakimRef: "JAKIM-COL-H01",
    halal_alternative: "E162 Beetroot Red or E160c Paprika Extract",
    trusted_suppliers: ["Naturex Malaysia Sdn Bhd", "Chr. Hansen Halal Division", "GNT Group (EXBERRY® line)"],
  },
  {
    name: "E122 — Carmoisine",
    aliases: ["Azorubine", "Food Red 3"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic azo dye. No biological or animal-derived components. Halal.",
    jakimRef: "JAKIM-COL-005",
  },
  {
    name: "E124 — Ponceau 4R",
    aliases: ["Cochineal Red A", "Brilliant Scarlet 4R"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic red azo dye produced from petroleum. No animal inputs. Halal under JAKIM.",
    jakimRef: "JAKIM-COL-006",
  },
  {
    name: "E129 — Allura Red AC",
    aliases: ["FD&C Red 40", "CI Food Red 17"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic azo dye. Widely used in drinks and confectionery. No animal-derived raw materials. Halal.",
    jakimRef: "JAKIM-COL-007",
  },
  {
    name: "E133 — Brilliant Blue FCF",
    aliases: ["FD&C Blue 1"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic triarylmethane dye. Petroleum-derived. No animal components. Halal.",
    jakimRef: "JAKIM-COL-008",
  },
  {
    name: "E150a — Plain Caramel",
    aliases: ["Caramel colour Class I"],
    status: "halal",
    category: "Colorant",
    description: "Produced by controlled heat treatment of sugar. No ammonia or sulphite compounds used. Plant-origin. Halal.",
    jakimRef: "JAKIM-COL-009",
  },
  {
    name: "E160a — Beta-Carotene",
    aliases: ["Provitamin A", "CI Food Orange 5"],
    status: "halal",
    category: "Colorant",
    description: "Orange pigment extracted from carrots or produced by microbial fermentation. Plant/microbial origin. Halal.",
    jakimRef: "JAKIM-COL-010",
  },
  {
    name: "E160b — Annatto",
    aliases: ["Bixin", "Norbixin", "Achiote"],
    status: "halal",
    category: "Colorant",
    description: "Natural orange-red dye from seeds of Bixa orellana. Plant-derived. Halal.",
    jakimRef: "JAKIM-COL-011",
  },
  {
    name: "E160c — Paprika Extract",
    aliases: ["Capsanthin", "Capsorubin"],
    status: "halal",
    category: "Colorant",
    description: "Red pigment extracted from paprika peppers. Fully plant-derived. Halal.",
    jakimRef: "JAKIM-COL-012",
  },
  {
    name: "E162 — Beetroot Red",
    aliases: ["Betanin", "Beet Red"],
    status: "halal",
    category: "Colorant",
    description: "Natural red pigment extracted from red beetroot. Plant-derived. Halal.",
    jakimRef: "JAKIM-COL-013",
  },

  // ── PRESERVATIVES ──────────────────────────────────────────────────────────

  {
    name: "E200 — Sorbic Acid",
    aliases: ["2,4-Hexadienoic acid"],
    status: "halal",
    category: "Preservative",
    description: "Synthetic antimicrobial preservative. Produced by chemical synthesis. No animal components. Halal.",
    jakimRef: "JAKIM-PRE-001",
  },
  {
    name: "E202 — Potassium Sorbate",
    aliases: ["Sorbic acid potassium salt"],
    status: "halal",
    category: "Preservative",
    description: "Salt of sorbic acid. Synthetic origin. Widely used in bakery and dairy. No animal inputs. Halal.",
    jakimRef: "JAKIM-PRE-002",
  },
  {
    name: "E210 — Benzoic Acid",
    aliases: ["Benzenecarboxylic acid"],
    status: "halal",
    category: "Preservative",
    description: "Synthetic preservative found naturally in cranberries. Produced by chemical oxidation of toluene. No animal components. Halal.",
    jakimRef: "JAKIM-PRE-003",
  },
  {
    name: "E211 — Sodium Benzoate",
    aliases: ["Benzoate of soda"],
    status: "halal",
    category: "Preservative",
    description: "Sodium salt of benzoic acid. Synthetic. Common in soft drinks and condiments. Halal.",
    jakimRef: "JAKIM-PRE-004",
  },
  {
    name: "E220 — Sulphur Dioxide",
    aliases: ["Sulfur dioxide", "SO₂"],
    status: "halal",
    category: "Preservative",
    description: "Inorganic preservative and antioxidant. Produced from burning sulphur. No biological origin. Halal.",
    jakimRef: "JAKIM-PRE-005",
  },
  {
    name: "E250 — Sodium Nitrite",
    aliases: ["Chile saltpetre"],
    status: "halal",
    category: "Preservative",
    description: "Inorganic salt used in cured meats. Mineral-derived. Halal in itself — permissibility depends on the meat it preserves.",
    jakimRef: "JAKIM-PRE-006",
  },
  {
    name: "E282 — Calcium Propionate",
    aliases: ["Calcium propanoate"],
    status: "halal",
    category: "Preservative",
    description: "Calcium salt of propionic acid. Produced by chemical synthesis from ethylene. Halal.",
    jakimRef: "JAKIM-PRE-007",
  },

  // ── ANTIOXIDANTS ───────────────────────────────────────────────────────────

  {
    name: "E300 — Ascorbic Acid",
    aliases: ["Vitamin C", "L-Ascorbic acid"],
    status: "halal",
    category: "Antioxidant",
    description: "Vitamin C produced by fermentation of glucose or chemical synthesis. No animal origin. Universally halal.",
    jakimRef: "JAKIM-ANT-001",
  },
  {
    name: "E301 — Sodium Ascorbate",
    aliases: ["Sodium L-ascorbate"],
    status: "halal",
    category: "Antioxidant",
    description: "Sodium salt of ascorbic acid. Synthetic. Halal.",
    jakimRef: "JAKIM-ANT-002",
  },
  {
    name: "E306 — Tocopherols",
    aliases: ["Mixed tocopherols", "Vitamin E"],
    status: "halal",
    category: "Antioxidant",
    description: "Natural form of Vitamin E extracted from vegetable oils (soy, sunflower). Plant-derived. Halal.",
    jakimRef: "JAKIM-ANT-003",
  },
  {
    name: "E320 — BHA",
    aliases: ["Butylated hydroxyanisole"],
    status: "halal",
    category: "Antioxidant",
    description: "Synthetic antioxidant. Petroleum-derived. No animal components. Halal.",
    jakimRef: "JAKIM-ANT-004",
  },
  {
    name: "E321 — BHT",
    aliases: ["Butylated hydroxytoluene"],
    status: "halal",
    category: "Antioxidant",
    description: "Synthetic antioxidant. Petroleum-derived. No animal components. Halal.",
    jakimRef: "JAKIM-ANT-005",
  },

  // ── ACIDS & ACIDITY REGULATORS ─────────────────────────────────────────────

  {
    name: "E260 — Acetic Acid",
    aliases: ["Ethanoic acid", "Vinegar acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Produced by fermentation of ethanol or by chemical synthesis. Plant/synthetic origin. Halal. Note: fermented from halal source only.",
    jakimRef: "JAKIM-ACR-001",
  },
  {
    name: "E270 — Lactic Acid",
    aliases: ["2-Hydroxypropanoic acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Produced by bacterial fermentation of carbohydrates (glucose, sucrose). No animal inputs required. Halal when bacterial culture medium is halal-compliant.",
    jakimRef: "JAKIM-ACR-002",
  },
  {
    name: "E296 — Malic Acid",
    aliases: ["Apple acid", "DL-Malic acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Found naturally in apples; commercially produced by chemical synthesis. Plant/synthetic. Halal.",
    jakimRef: "JAKIM-ACR-003",
  },
  {
    name: "E330 — Citric Acid",
    aliases: ["2-Hydroxypropane-1,2,3-tricarboxylic acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Produced by fermentation of sucrose using Aspergillus niger mould. No animal inputs. Universally halal.",
    jakimRef: "JAKIM-ACR-004",
  },
  {
    name: "E334 — Tartaric Acid",
    aliases: ["L(+)-Tartaric acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Naturally occurring in grapes; commercially extracted as a by-product of winemaking. Plant-derived. Halal.",
    jakimRef: "JAKIM-ACR-005",
  },
  {
    name: "E338 — Phosphoric Acid",
    aliases: ["Orthophosphoric acid"],
    status: "halal",
    category: "Acidity Regulator",
    description: "Mineral acid produced from phosphate rock. No biological origin. Halal.",
    jakimRef: "JAKIM-ACR-006",
  },

  // ── THICKENERS & STABILISERS ───────────────────────────────────────────────

  {
    name: "E400 — Alginic Acid",
    aliases: ["Alginate"],
    status: "halal",
    category: "Thickener",
    description: "Polysaccharide extracted from brown seaweed. Marine plant origin. Halal.",
    jakimRef: "JAKIM-THK-001",
  },
  {
    name: "E401 — Sodium Alginate",
    aliases: ["Sodium polymannuronate"],
    status: "halal",
    category: "Thickener",
    description: "Sodium salt of alginic acid extracted from brown algae. Seaweed-derived. Halal.",
    jakimRef: "JAKIM-THK-002",
  },
  {
    name: "E406 — Agar",
    aliases: ["Agar-agar", "Kanten"],
    status: "halal",
    category: "Gelling Agent",
    description: "Polysaccharide extracted from red algae (Gelidium, Gracilaria). Seaweed-derived. Widely used as halal gelatin substitute.",
    jakimRef: "JAKIM-THK-003",
  },
  {
    name: "E407 — Carrageenan",
    aliases: ["Irish moss extract"],
    status: "halal",
    category: "Thickener",
    description: "Sulphated polysaccharide from red seaweed. Marine plant origin. Halal.",
    jakimRef: "JAKIM-THK-004",
  },
  {
    name: "E410 — Locust Bean Gum",
    aliases: ["Carob bean gum", "Ceratonia siliqua gum"],
    status: "halal",
    category: "Thickener",
    description: "Galactomannan extracted from seeds of the carob tree. Plant-derived. Halal.",
    jakimRef: "JAKIM-THK-005",
  },
  {
    name: "E412 — Guar Gum",
    aliases: ["Guaran"],
    status: "halal",
    category: "Thickener",
    description: "Galactomannan from seeds of the guar plant (Cyamopsis tetragonoloba). Plant-derived. Halal.",
    jakimRef: "JAKIM-THK-006",
  },
  {
    name: "E414 — Acacia Gum",
    aliases: ["Gum arabic", "Sudan gum arabic"],
    status: "halal",
    category: "Thickener",
    description: "Hardened sap from Acacia senegal and Acacia seyal trees. Plant-derived. Halal.",
    jakimRef: "JAKIM-THK-007",
  },
  {
    name: "E415 — Xanthan Gum",
    aliases: ["Corn sugar gum"],
    status: "halal",
    category: "Thickener",
    description: "Produced by bacterial fermentation of glucose by Xanthomonas campestris. Microbial origin. Halal when fermented on halal-compliant medium.",
    jakimRef: "JAKIM-THK-008",
  },
  {
    name: "E418 — Gellan Gum",
    aliases: ["Pseudomonas elodea polysaccharide"],
    status: "halal",
    category: "Thickener",
    description: "Microbial polysaccharide produced by Sphingomonas elodea fermentation. No animal inputs. Halal.",
    jakimRef: "JAKIM-THK-009",
  },
  {
    name: "E440 — Pectin",
    aliases: ["Fruit pectin", "Apple pectin"],
    status: "halal",
    category: "Gelling Agent",
    description: "Structural polysaccharide extracted from citrus peel or apple pomace. Plant-derived. Widely accepted halal alternative to gelatin.",
    jakimRef: "JAKIM-THK-010",
  },
  {
    name: "E460 — Cellulose",
    aliases: ["Microcrystalline cellulose", "MCC"],
    status: "halal",
    category: "Thickener",
    description: "Structural polysaccharide from plant cell walls. Plant-derived. Halal.",
    jakimRef: "JAKIM-THK-011",
  },
  {
    name: "E466 — Carboxymethyl Cellulose",
    aliases: ["CMC", "Sodium carboxymethyl cellulose"],
    status: "halal",
    category: "Thickener",
    description: "Chemically modified cellulose from plant pulp. Synthetic/plant. Halal.",
    jakimRef: "JAKIM-THK-012",
  },

  // ── EMULSIFIERS ────────────────────────────────────────────────────────────

  {
    name: "E322 — Lecithin",
    aliases: ["Soya lecithin", "Sunflower lecithin"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Phospholipid extracted from soy, sunflower, or egg yolk. When derived from soy or sunflower: halal. When from egg: halal if from halal hens. Verify source with supplier declaration. JAKIM requires source certification.",
    jakimRef: "JAKIM-EMU-D01",
    halal_alternative: "JAKIM-certified Sunflower Lecithin (non-GMO, plant-origin declaration required)",
    trusted_suppliers: ["Lipoid GmbH (Halal Certified)", "Sternchemie GmbH (SternPure® Sunflower)", "Bunge Loders Croklaan Malaysia"],
  },
  {
    name: "E422 — Glycerol",
    aliases: ["Glycerine", "Glycerin", "Propane-1,2,3-triol"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Can be derived from animal fats (including pork) or from plant oils (palm, soy) or synthetic sources. JAKIM requires supplier declaration of plant or synthetic origin. Frequently found in baked goods and confectionery.",
    jakimRef: "JAKIM-EMU-D02",
    halal_alternative: "Vegetable Glycerine (Palm-derived, JAKIM-certified)",
    trusted_suppliers: ["IOI Loders Croklaan (VegiPure®)", "KLK OLEO Sdn Bhd", "Emery Oleochemicals Malaysia"],
  },
  {
    name: "E441 — Gelatine",
    aliases: ["Gelatin", "Hydrolysed collagen"],
    status: "haram",
    category: "Gelling Agent",
    description: "Protein obtained by boiling animal skin, bones, and connective tissue. Commercially almost always pork-derived (porcine) unless explicitly labelled as bovine halal-certified or fish gelatin. HARAM unless JAKIM-certified halal source is confirmed.",
    jakimRef: "JAKIM-GEL-H01",
    halal_alternative: "Agar-Agar (E406), Pectin (E440), or JAKIM-certified Fish Gelatin",
    trusted_suppliers: ["CP Kelco (GENU® Pectin)", "Rousselot Halal (Fish Gelatin)", "AHD International Sdn Bhd (Agar)"],
  },
  {
    name: "E470a — Sodium, Potassium, Calcium Salts of Fatty Acids",
    aliases: ["Fatty acid salts"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Salts of fatty acids that may be derived from animal (including porcine) or plant sources. Source must be declared. JAKIM classifies as mashbooh without supplier certificate.",
    jakimRef: "JAKIM-EMU-D03",
    halal_alternative: "Palm-derived Fatty Acid Salts (JAKIM-certified)",
    trusted_suppliers: ["KLK OLEO Sdn Bhd", "Musim Mas Group", "Carotino Sdn Bhd"],
  },
  {
    name: "E471 — Mono and Diglycerides of Fatty Acids",
    aliases: ["Glyceryl monostearate", "GMS", "MDG"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Emulsifiers derived from glycerol and fatty acids. Source can be animal fat (including pork lard) or vegetable oils. Extremely common in bakery, margarine, and ice cream. JAKIM requires plant-origin or halal-slaughter certification. One of the most flagged additives in Malaysian halal audits.",
    jakimRef: "JAKIM-EMU-D04",
    halal_alternative: "Palm-origin Mono & Diglycerides (JAKIM MS1500:2019 certified)",
    trusted_suppliers: ["Bunge Loders Croklaan (Dimodan® Halal)", "IOI Oleo GmbH", "AAK Malaysia Sdn Bhd"],
  },
  {
    name: "E472a — Acetic Acid Esters of Mono and Diglycerides",
    aliases: ["Acetem"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Ester of acetic acid and mono/diglycerides. Source of glycerides can be animal or plant. JAKIM requires source declaration.",
    jakimRef: "JAKIM-EMU-D05",
    halal_alternative: "Plant-origin Acetem (palm-based, JAKIM-declared)",
    trusted_suppliers: ["Palsgaard Malaysia", "Danisco (DuPont) Halal Range", "Corbion Purac Malaysia"],
  },
  {
    name: "E472b — Lactic Acid Esters of Mono and Diglycerides",
    aliases: ["Lactem", "Lactiglycerides"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Ester of lactic acid and mono/diglycerides. Source ambiguity same as E471. Requires halal certification.",
    jakimRef: "JAKIM-EMU-D06",
    halal_alternative: "JAKIM-certified Lactic Acid Esters from palm-derived glycerides",
    trusted_suppliers: ["Palsgaard Malaysia", "Corbion Purac Malaysia", "Bunge Loders Croklaan (Halal)"],
  },
  {
    name: "E472e — Diacetyltartaric Acid Esters of Mono and Diglycerides",
    aliases: ["DATEM"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Complex ester used as dough conditioner. Glyceride component may be animal-derived. Requires halal supplier declaration.",
    jakimRef: "JAKIM-EMU-D07",
    halal_alternative: "Plant-origin DATEM with JAKIM or IFANCA certification",
    trusted_suppliers: ["Puratos Group (Halal Certified)", "Beldem Sdn Bhd", "Aarhus Karlshamn Malaysia"],
  },
  {
    name: "E481 — Sodium Stearoyl Lactylate",
    aliases: ["SSL"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Sodium salt of stearic acid esterified with lactic acid. Stearic acid can be from animal fat (pork) or plant (palm). Widely used in bread. JAKIM classifies as mashbooh — plant-origin SSL is halal, animal-origin is not.",
    jakimRef: "JAKIM-EMU-D08",
    halal_alternative: "Palm-origin SSL (Sodium Stearoyl Lactylate) with JAKIM MS1500 certification",
    trusted_suppliers: ["Corbion Purac Malaysia (PURAC® FCC)", "Stepan Company (Halal Grade)", "Lonza Malaysia Sdn Bhd"],
  },
  {
    name: "E482 — Calcium Stearoyl Lactylate",
    aliases: ["CSL"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Calcium salt equivalent of SSL. Same source ambiguity. Requires plant-origin certification from supplier.",
    jakimRef: "JAKIM-EMU-D09",
    halal_alternative: "Palm-origin CSL with JAKIM-certified supplier declaration",
    trusted_suppliers: ["Corbion Purac Malaysia", "Stepan Company (Halal Grade)", "Lonza Malaysia Sdn Bhd"],
  },
  {
    name: "E491 — Sorbitan Monostearate",
    aliases: ["Span 60"],
    status: "doubtful",
    category: "Emulsifier",
    description: "Ester of sorbitol and stearic acid. Stearic acid may be animal- or plant-derived. Source must be verified. JAKIM mashbooh without certificate.",
    jakimRef: "JAKIM-EMU-D10",
    halal_alternative: "Plant-derived Sorbitan Monostearate (palm stearic acid, JAKIM certified)",
    trusted_suppliers: ["Croda Sdn Bhd (Halal Certified)", "Nikkol Group Malaysia", "Evonik Industries (Halal Line)"],
  },

  // ── SWEETENERS ─────────────────────────────────────────────────────────────

  {
    name: "E420 — Sorbitol",
    aliases: ["Glucitol", "D-Sorbitol"],
    status: "halal",
    category: "Sweetener",
    description: "Sugar alcohol produced by hydrogenation of glucose (from corn starch). Synthetic/plant. Halal.",
    jakimRef: "JAKIM-SWT-001",
  },
  {
    name: "E421 — Mannitol",
    aliases: ["D-Mannitol"],
    status: "halal",
    category: "Sweetener",
    description: "Sugar alcohol found naturally in seaweed and mushrooms; commercially produced by hydrogenation of fructose. Halal.",
    jakimRef: "JAKIM-SWT-002",
  },
  {
    name: "E950 — Acesulfame Potassium",
    aliases: ["Acesulfame K", "Ace-K"],
    status: "halal",
    category: "Sweetener",
    description: "Synthetic high-intensity sweetener. No biological origin. 200× sweeter than sugar. Halal.",
    jakimRef: "JAKIM-SWT-003",
  },
  {
    name: "E951 — Aspartame",
    aliases: ["NutraSweet", "Equal"],
    status: "halal",
    category: "Sweetener",
    description: "Dipeptide methyl ester. Synthesised from aspartic acid and phenylalanine — both produced by microbial fermentation on halal media. JAKIM-certified halal.",
    jakimRef: "JAKIM-SWT-004",
  },
  {
    name: "E955 — Sucralose",
    aliases: ["Splenda", "Trichlorogalactosucrose"],
    status: "halal",
    category: "Sweetener",
    description: "Made by selective chlorination of sucrose. Synthetic. No animal inputs. Halal.",
    jakimRef: "JAKIM-SWT-005",
  },
  {
    name: "E960 — Steviol Glycosides",
    aliases: ["Stevia", "Rebaudioside A"],
    status: "halal",
    category: "Sweetener",
    description: "Naturally occurring glycosides extracted from Stevia rebaudiana leaves. Plant-derived. Halal.",
    jakimRef: "JAKIM-SWT-006",
  },

  // ── FLAVOUR ENHANCERS ──────────────────────────────────────────────────────

  {
    name: "E620 — Glutamic Acid",
    aliases: ["L-Glutamic acid"],
    status: "halal",
    category: "Flavour Enhancer",
    description: "Amino acid produced by microbial fermentation of plant-based sugars. No animal inputs used commercially. Halal.",
    jakimRef: "JAKIM-FLV-001",
  },
  {
    name: "E621 — Monosodium Glutamate",
    aliases: ["MSG", "Sodium glutamate", "Aji-no-moto"],
    status: "halal",
    category: "Flavour Enhancer",
    description: "Sodium salt of glutamic acid. Produced by bacterial fermentation of sugarcane molasses or tapioca starch. No animal components. Halal — frequently misunderstood as haram without basis in JAKIM standards.",
    jakimRef: "JAKIM-FLV-002",
  },
  {
    name: "E627 — Disodium Guanylate",
    aliases: ["Sodium 5′-guanylate", "DSG"],
    status: "doubtful",
    category: "Flavour Enhancer",
    description: "Nucleotide flavour enhancer. Can be derived from yeast extract (halal), fish (halal), or pork (haram). Frequently used together with MSG. JAKIM requires source declaration.",
    jakimRef: "JAKIM-FLV-D01",
    halal_alternative: "Yeast-derived Disodium Guanylate or Fish-sourced DSG (JAKIM certified)",
    trusted_suppliers: ["Ajinomoto Malaysia Bhd (Halal Certified)", "Kohjin Life Sciences", "Angel Yeast Malaysia"],
  },
  {
    name: "E631 — Disodium Inosinate",
    aliases: ["Sodium 5′-inosinate", "DSI"],
    status: "doubtful",
    category: "Flavour Enhancer",
    description: "Nucleotide flavour enhancer. Can be produced from sardines/fish (halal), yeast (halal), or porcine sources (haram). Without clear source declaration, JAKIM classifies as mashbooh. Often found in instant noodles and snack seasoning.",
    jakimRef: "JAKIM-FLV-D02",
    halal_alternative: "Fish-derived or Yeast-derived Disodium Inosinate (JAKIM-certified source)",
    trusted_suppliers: ["Ajinomoto Malaysia Bhd", "CJ CheilJedang (Halal Division)", "Kohjin Life Sciences"],
  },
  {
    name: "E635 — Disodium Ribonucleotides",
    aliases: ["Sodium 5′-ribonucleotides"],
    status: "doubtful",
    category: "Flavour Enhancer",
    description: "Mixture of disodium inosinate (E631) and disodium guanylate (E627). Inherits the same source ambiguity. JAKIM mashbooh — requires certification.",
    jakimRef: "JAKIM-FLV-D03",
    halal_alternative: "Yeast Extract-based Flavour Enhancer (Halal-certified 5′-Ribonucleotides)",
    trusted_suppliers: ["Ajinomoto Malaysia Bhd", "Angel Yeast Malaysia", "Biospringer Sdn Bhd"],
  },

  // ── RAISING AGENTS ─────────────────────────────────────────────────────────

  {
    name: "E500 — Sodium Carbonates",
    aliases: ["Sodium carbonate", "Baking soda", "Sodium bicarbonate"],
    status: "halal",
    category: "Raising Agent",
    description: "Inorganic mineral compounds. Produced from trona ore or Solvay process. No biological inputs. Halal.",
    jakimRef: "JAKIM-RAI-001",
  },
  {
    name: "E503 — Ammonium Carbonates",
    aliases: ["Ammonium carbonate", "Baker's ammonia"],
    status: "halal",
    category: "Raising Agent",
    description: "Inorganic ammonium salt. Synthetic. Decomposes completely during baking. Halal.",
    jakimRef: "JAKIM-RAI-002",
  },
  {
    name: "E516 — Calcium Sulphate",
    aliases: ["Gypsum", "Plaster of Paris"],
    status: "halal",
    category: "Raising Agent",
    description: "Naturally occurring mineral. No biological origin. Used as flour treatment agent. Halal.",
    jakimRef: "JAKIM-RAI-003",
  },

  // ── ANTI-CAKING & MINERALS ─────────────────────────────────────────────────

  {
    name: "E551 — Silicon Dioxide",
    aliases: ["Silica", "Amorphous silicon dioxide"],
    status: "halal",
    category: "Anti-caking Agent",
    description: "Mineral compound. Mined from quartz or produced synthetically. No biological origin. Halal.",
    jakimRef: "JAKIM-MIN-001",
  },
  {
    name: "E170 — Calcium Carbonate",
    aliases: ["Chalk", "Limestone", "CaCO₃"],
    status: "halal",
    category: "Mineral",
    description: "Naturally occurring mineral. Mined from limestone deposits. No biological origin. Halal.",
    jakimRef: "JAKIM-MIN-002",
  },
  {
    name: "E172 — Iron Oxides and Hydroxides",
    aliases: ["Iron oxide red", "Iron oxide yellow", "Iron oxide black"],
    status: "halal",
    category: "Mineral Colorant",
    description: "Inorganic iron compounds. Mineral origin. Used in confectionery coatings. Halal.",
    jakimRef: "JAKIM-MIN-003",
  },
  {
    name: "E509 — Calcium Chloride",
    aliases: ["CaCl₂"],
    status: "halal",
    category: "Firming Agent",
    description: "Inorganic mineral salt. Produced from limestone or as a by-product of the Solvay process. No biological inputs. Halal.",
    jakimRef: "JAKIM-MIN-004",
  },

  // ── PHOSPHATES ─────────────────────────────────────────────────────────────

  {
    name: "E450 — Diphosphates",
    aliases: ["Sodium diphosphate", "Sodium pyrophosphate"],
    status: "halal",
    category: "Raising Agent",
    description: "Inorganic phosphate salt. Produced from phosphoric acid and sodium salts. No biological origin. Halal.",
    jakimRef: "JAKIM-PHO-001",
  },
  {
    name: "E451 — Triphosphates",
    aliases: ["Sodium triphosphate", "STPP"],
    status: "halal",
    category: "Raising Agent",
    description: "Inorganic phosphate salt. Mineral/synthetic. No animal origin. Halal.",
    jakimRef: "JAKIM-PHO-002",
  },
  {
    name: "E452 — Polyphosphates",
    aliases: ["Sodium polyphosphate", "Sodium hexametaphosphate"],
    status: "halal",
    category: "Stabiliser",
    description: "Inorganic polyphosphate salt. Synthetic/mineral. Halal.",
    jakimRef: "JAKIM-PHO-003",
  },

  // ── FATS & FATTY ACID DERIVATIVES ─────────────────────────────────────────

  {
    name: "E570 — Fatty Acids",
    aliases: ["Stearic acid", "Palmitic acid", "Oleic acid"],
    status: "doubtful",
    category: "Anti-caking Agent",
    description: "Fatty acids used as anti-caking, glazing, and foam-control agents. Derived from animal fats (including pork), vegetable oils (palm, soy), or synthetically. JAKIM classifies as mashbooh — plant-origin certification required.",
    jakimRef: "JAKIM-FAT-D01",
    halal_alternative: "Palm Stearic Acid / Palm Palmitic Acid (JAKIM MS1500 certified)",
    trusted_suppliers: ["KLK OLEO Sdn Bhd", "Musim Mas Group (Halal Certified)", "IOI Corporation Bhd Oleochemicals"],
  },
  {
    name: "E542 — Bone Phosphate",
    aliases: ["Edible bone phosphate", "Calcium phosphate from bone"],
    status: "haram",
    category: "Anti-caking Agent",
    description: "Calcium phosphate obtained by calcination of animal bones. Unless bones are from JAKIM-certified halal-slaughtered animals, this is considered HARAM. Commonly porcine-sourced in non-halal production.",
    jakimRef: "JAKIM-FAT-H01",
    halal_alternative: "E341 Tricalcium Phosphate (mineral/synthetic origin) or E170 Calcium Carbonate",
    trusted_suppliers: ["ICL Food Specialties (Halal Grade)", "Budenheim Malaysia Sdn Bhd", "Prayon SA (Mineral Phosphates)"],
  },

  // ── COMMON INGREDIENTS (non-E-number) ─────────────────────────────────────

  {
    name: "Lard",
    aliases: ["Pig fat", "Pork fat", "Saindoux", "Strutto"],
    status: "haram",
    category: "Fat",
    description: "Rendered fat from pigs. Strictly HARAM in Islam. Used in pastries, frying shortenings, and some processed foods. One of the most critical haram ingredients in Malaysian product audits.",
    jakimRef: "JAKIM-FAT-H02",
    halal_alternative: "Vegetable Shortening (palm olein / palm kernel oil) or Coconut Oil",
    trusted_suppliers: ["Golden Jomalina Food Industries Sdn Bhd", "Lam Soon Malaysia (Naturel® Palm)", "AAK Malaysia Sdn Bhd (Halal Shortenings)"],
  },
  {
    name: "Gelatine (Porcine)",
    aliases: ["Pork gelatin", "Pig gelatin", "Porcine gelatin"],
    status: "haram",
    category: "Gelling Agent",
    description: "Protein derived from porcine (pig) skin, bones, and connective tissue. Strictly HARAM. Common in gummy sweets, marshmallows, yoghurt, and capsule shells. Must be replaced with agar, pectin, or JAKIM-certified bovine/fish gelatin.",
    jakimRef: "JAKIM-GEL-H02",
    halal_alternative: "Agar-Agar (E406), Carrageenan (E407), or JAKIM-certified Fish Gelatin",
    trusted_suppliers: ["Rousselot Halal (Fish & Bovine Halal Gelatin)", "Nitta Gelatin (Halal Division)", "AHD International Sdn Bhd"],
  },
  {
    name: "Gelatine (Bovine)",
    aliases: ["Beef gelatin", "Halal gelatin"],
    status: "doubtful",
    category: "Gelling Agent",
    description: "Gelatin from cattle. Halal only if cattle were slaughtered according to Islamic rites and certified by JAKIM or equivalent body. Without certification, classified as mashbooh.",
    jakimRef: "JAKIM-GEL-D01",
    halal_alternative: "JAKIM-certified Bovine Halal Gelatin or Fish Gelatin (E441 Fish-based)",
    trusted_suppliers: ["Rousselot Halal (Bovine HiPure®)", "Nitta Gelatin (Halal Grade)", "Lapi Gelatine Sdn Bhd"],
  },
  {
    name: "Gelatine (Fish)",
    aliases: ["Marine gelatin", "Fish skin gelatin"],
    status: "halal",
    category: "Gelling Agent",
    description: "Gelatin extracted from fish skin and scales. Considered halal by JAKIM — fish do not require slaughter. Increasingly used as halal alternative in capsules and confectionery.",
    jakimRef: "JAKIM-GEL-001",
  },
  {
    name: "Lecithin (Soy)",
    aliases: ["Soya lecithin", "Soybean lecithin"],
    status: "halal",
    category: "Emulsifier",
    description: "Phospholipid by-product of soybean oil processing. Plant-derived. Widely certified halal by JAKIM. Verify no animal carrier used in processing.",
    jakimRef: "JAKIM-EMU-001",
  },
  {
    name: "Lecithin (Egg)",
    aliases: ["Egg lecithin", "Ovothin"],
    status: "halal",
    category: "Emulsifier",
    description: "Phospholipid from egg yolk. Halal if eggs are from halal-compliant hens. JAKIM accepts egg lecithin with proper declaration.",
    jakimRef: "JAKIM-EMU-002",
  },
  {
    name: "Pectin",
    aliases: ["Apple pectin", "Citrus pectin", "Fruit pectin"],
    status: "halal",
    category: "Gelling Agent",
    description: "Structural polysaccharide from citrus peels or apple pomace. Fully plant-derived. Widely accepted halal substitute for gelatin in jams, jellies, and confectionery.",
    jakimRef: "JAKIM-THK-013",
  },
  {
    name: "Rennet (Animal)",
    aliases: ["Calf rennet", "Chymosin (animal)"],
    status: "doubtful",
    category: "Coagulant",
    description: "Enzyme complex extracted from the stomach lining of ruminants. Halal only if animal was slaughtered according to Islamic rites. Non-certified animal rennet is mashbooh. Used in cheese production.",
    jakimRef: "JAKIM-ENZ-D01",
    halal_alternative: "Microbial Rennet (Chymosin from Aspergillus niger) or Vegetable Rennet",
    trusted_suppliers: ["Chr. Hansen Halal Division (CHY-MAX® M)", "DSM Food Specialties (MaxiRen®)", "Enzymatica Malaysia Sdn Bhd"],
  },
  {
    name: "Rennet (Microbial)",
    aliases: ["Microbial chymosin", "Fermentation-produced chymosin", "FPC"],
    status: "halal",
    category: "Coagulant",
    description: "Chymosin produced by genetically engineered microorganisms (Aspergillus niger, Kluyveromyces lactis). No animal slaughter required. JAKIM-accepted halal coagulant for cheese.",
    jakimRef: "JAKIM-ENZ-001",
  },
  {
    name: "Whey Protein",
    aliases: ["Whey protein concentrate", "WPC", "Whey protein isolate", "WPI"],
    status: "doubtful",
    category: "Protein",
    description: "By-product of cheese making. Halal only if the dairy source used halal-certified rennet and the processing conditions are halal. Without supplier certification, JAKIM classifies as mashbooh. Critical in sports nutrition products.",
    jakimRef: "JAKIM-PRO-D01",
    halal_alternative: "Pea Protein Isolate, Soy Protein Isolate, or JAKIM-certified Halal Whey",
    trusted_suppliers: ["Roquette Malaysia (NUTRALYS® Pea Protein)", "Fonterra Halal (New Zealand)", "Arla Foods Ingredients (Halal Whey)"],
  },
  {
    name: "Casein",
    aliases: ["Sodium caseinate", "Calcium caseinate"],
    status: "doubtful",
    category: "Protein",
    description: "Milk protein coagulated using rennet or acid. If rennet-coagulated: requires halal rennet certification. Acid-coagulated casein using lactic acid is generally halal. Source verification required.",
    jakimRef: "JAKIM-PRO-D02",
    halal_alternative: "Acid-coagulated Halal Casein or Pea/Soy Protein Caseinate alternative",
    trusted_suppliers: ["Fonterra Halal (Acid Casein)", "Murray Goulburn (Halal Certified)", "Roquette Malaysia (Plant Proteins)"],
  },
  {
    name: "Carmine (Natural Red 4)",
    aliases: ["Cochineal extract", "CI 75470"],
    status: "haram",
    category: "Colorant",
    description: "Red dye from female cochineal insects (Dactylopius coccus). Insect-derived. HARAM under JAKIM fatwa. Found hidden in strawberry-flavoured products, juices, yoghurts, and lipsticks.",
    jakimRef: "JAKIM-COL-H02",
    halal_alternative: "E162 Beetroot Red, E163 Anthocyanins, or E160c Paprika Extract",
    trusted_suppliers: ["GNT Group (EXBERRY® Natural Colours)", "Naturex Malaysia Sdn Bhd", "Sensient Technologies (Halal Line)"],
  },
  {
    name: "L-Cysteine (E920)",
    aliases: ["Cysteine", "L-Cysteine hydrochloride"],
    status: "doubtful",
    category: "Flour Treatment Agent",
    description: "Amino acid used as dough conditioner. Can be derived from human hair, poultry feathers, or pig bristles (haram), or produced synthetically/microbially (halal). Source must be declared. JAKIM mashbooh without certificate.",
    jakimRef: "JAKIM-FTA-D01",
    halal_alternative: "Synthetic or Fermentation-derived L-Cysteine HCl (JAKIM-certified)",
    trusted_suppliers: ["Wacker Chemie (synthetic L-Cysteine)", "Ajinomoto Malaysia Bhd (fermented)", "Evonik Industries (Biopharma Grade Halal)"],
  },
  {
    name: "Shellac (E904)",
    aliases: ["Lac resin", "Lacca"],
    status: "haram",
    category: "Glazing Agent",
    description: "Resin secreted by the female lac bug (Kerria lacca). Insect-derived. HARAM under JAKIM standards. Used as a glazing agent on apples, confectionery, and pharmaceutical coatings.",
    jakimRef: "JAKIM-GLZ-H01",
    halal_alternative: "E903 Carnauba Wax or E901 Beeswax (plant/bee-origin, JAKIM accepted)",
    trusted_suppliers: ["Koster Keunen Wax (Carnauba)", "Norevo GmbH (Halal Waxes)", "Paramelt Malaysia Sdn Bhd"],
  },
  {
    name: "Beeswax (E901)",
    aliases: ["White beeswax", "Yellow beeswax"],
    status: "halal",
    category: "Glazing Agent",
    description: "Wax produced by honey bees. Insects that produce wax are not considered najis (impure) under JAKIM interpretation. JAKIM classifies beeswax as halal. Used as glazing agent on fruits and confectionery.",
    jakimRef: "JAKIM-GLZ-001",
  },
  {
    name: "Carnauba Wax (E903)",
    aliases: ["Brazil wax", "Palm wax"],
    status: "halal",
    category: "Glazing Agent",
    description: "Wax from leaves of the carnauba palm (Copernicia prunifera). Plant-derived. Halal.",
    jakimRef: "JAKIM-GLZ-002",
  },
  {
    name: "Glycerine (Plant-derived)",
    aliases: ["Vegetable glycerine", "Palm glycerol"],
    status: "halal",
    category: "Humectant",
    description: "Glycerol produced from palm oil or soy oil by-products. Fully plant-derived. Halal when source is confirmed as plant-origin with supplier declaration.",
    jakimRef: "JAKIM-HUM-001",
  },
  {
    name: "Propylene Glycol (E1520)",
    aliases: ["1,2-Propanediol"],
    status: "halal",
    category: "Humectant",
    description: "Synthetic diol produced from propylene oxide (petroleum). No biological origin. Halal.",
    jakimRef: "JAKIM-HUM-002",
  },
  {
    name: "Yeast Extract",
    aliases: ["Autolysed yeast", "Hydrolysed yeast"],
    status: "halal",
    category: "Flavouring",
    description: "Product of autolysis of yeast cells (Saccharomyces cerevisiae). Yeast is a halal organism. Widely used in savoury flavourings. Halal — verify no porcine-based growth medium is used.",
    jakimRef: "JAKIM-FLV-003",
  },
  {
    name: "Natural Flavouring",
    aliases: ["Natural flavour", "Natural flavour extract"],
    status: "doubtful",
    category: "Flavouring",
    description: "Broad category: can be derived from plant, animal, or microbial sources. JAKIM requires full disclosure of flavouring source. Without declaration, classified as mashbooh. Beaver anal gland (castoreum), used as vanilla flavouring, is haram.",
    jakimRef: "JAKIM-FLV-D04",
    halal_alternative: "Plant-origin Natural Flavouring with full JAKIM disclosure, or Vanilla Extract (E160c)",
    trusted_suppliers: ["Givaudan Halal Flavours Division", "IFF (International Flavors & Fragrances) Halal", "Symrise Malaysia Sdn Bhd"],
  },
  {
    name: "Vanilla Extract",
    aliases: ["Pure vanilla", "Vanilla bean extract"],
    status: "halal",
    category: "Flavouring",
    description: "Extracted from vanilla beans (Vanilla planifolia) using ethanol solution. Plant-derived. JAKIM permits vanilla extract; the residual alcohol from extraction is considered negligible and not intoxicating.",
    jakimRef: "JAKIM-FLV-004",
  },
  {
    name: "Palm Oil",
    aliases: ["Elaeis guineensis oil"],
    status: "halal",
    category: "Fat",
    description: "Oil extracted from fruit of the oil palm. Plant-derived. Certified halal by JAKIM. Malaysia's primary cooking and industrial oil. MSPO-certified sources are halal.",
    jakimRef: "JAKIM-FAT-001",
  },
  {
    name: "Soybean Oil",
    aliases: ["Soy oil", "Soya oil"],
    status: "halal",
    category: "Fat",
    description: "Oil pressed from soybeans. Plant-derived. No animal inputs. Halal.",
    jakimRef: "JAKIM-FAT-002",
  },
  {
    name: "Hydrogenated Vegetable Oil",
    aliases: ["Partially hydrogenated oil", "PHO", "Vegetable shortening"],
    status: "halal",
    category: "Fat",
    description: "Vegetable oil (palm, soy, canola) treated with hydrogen to increase saturation. Plant-derived. The hydrogenation catalyst (nickel) is removed. Halal when base oil is plant-origin.",
    jakimRef: "JAKIM-FAT-003",
  },
  {
    name: "Tallow",
    aliases: ["Beef tallow", "Mutton tallow", "Rendered animal fat"],
    status: "doubtful",
    category: "Fat",
    description: "Hard fat rendered from cattle or sheep. Halal only if from JAKIM-certified halal-slaughtered animals. Without certification, mashbooh. Used in frying oils, shortenings, and as carrier in flavourings.",
    jakimRef: "JAKIM-FAT-D02",
    halal_alternative: "Palm Stearin or Vegetable Shortening (JAKIM-certified plant-origin)",
    trusted_suppliers: ["Golden Jomalina Food Industries Sdn Bhd", "Lam Soon Malaysia (Naturel®)", "IOI Corporation Bhd Oleochemicals"],
  },
  {
    name: "Sodium Lauryl Sulphate (E487)",
    aliases: ["SLS", "Sodium dodecyl sulphate"],
    status: "halal",
    category: "Emulsifier",
    description: "Surfactant produced synthetically from lauryl alcohol (coconut or palm-derived). Plant/synthetic. No animal inputs. Halal.",
    jakimRef: "JAKIM-EMU-003",
  },
  {
    name: "Carob Bean Gum (E410)",
    aliases: ["Locust bean gum", "LBG"],
    status: "halal",
    category: "Thickener",
    description: "Galactomannan from carob seeds. Plant-derived. Halal.",
    jakimRef: "JAKIM-THK-014",
  },
  {
    name: "Modified Starch (E1400–E1450)",
    aliases: ["Hydroxypropyl starch", "Acetylated starch", "Oxidised starch"],
    status: "halal",
    category: "Thickener",
    description: "Chemically modified starches from corn, potato, tapioca, or wheat. Plant-derived. No animal inputs in modification process. Halal.",
    jakimRef: "JAKIM-THK-015",
  },
  {
    name: "Sodium Alginate (E401)",
    aliases: ["Algin"],
    status: "halal",
    category: "Thickener",
    description: "Sodium salt of alginic acid from brown seaweed. Marine plant. Halal.",
    jakimRef: "JAKIM-THK-016",
  },
  {
    name: "Potassium Nitrate (E252)",
    aliases: ["Saltpetre", "KNO₃"],
    status: "halal",
    category: "Preservative",
    description: "Inorganic mineral salt used in cured meats. No biological origin. Halal as an additive — permissibility depends on the product it preserves.",
    jakimRef: "JAKIM-PRE-008",
  },
  {
    name: "Amylase",
    aliases: ["Alpha-amylase", "Fungal amylase"],
    status: "halal",
    category: "Enzyme",
    description: "Enzyme that breaks down starch. Commercially produced from Aspergillus oryzae (fungal) or Bacillus subtilis (bacterial). Microbial origin. Halal when fermented on halal media.",
    jakimRef: "JAKIM-ENZ-002",
  },
  {
    name: "Lipase",
    aliases: ["Pancreatic lipase", "Microbial lipase"],
    status: "doubtful",
    category: "Enzyme",
    description: "Fat-digesting enzyme. Can be sourced from porcine pancreas (haram), bovine/ovine pancreas (halal if halal-slaughtered), or microbial fermentation (halal). Source must be declared. Used in cheese and bakery.",
    jakimRef: "JAKIM-ENZ-D02",
    halal_alternative: "Microbial Lipase from Aspergillus oryzae or Rhizomucor miehei (JAKIM-certified)",
    trusted_suppliers: ["Novozymes Halal Division (Lipozyme®)", "DSM Food Specialties (Halal Lipase)", "Amano Enzyme Malaysia"],
  },
  {
    name: "Protease",
    aliases: ["Bromelain", "Papain", "Subtilisin"],
    status: "halal",
    category: "Enzyme",
    description: "Protein-digesting enzymes from plant (bromelain from pineapple, papain from papaya) or microbial fermentation. Plant/microbial origin. Halal.",
    jakimRef: "JAKIM-ENZ-003",
  },
  {
    name: "Tartrazine (E102)",
    aliases: ["FD&C Yellow 5"],
    status: "halal",
    category: "Colorant",
    description: "Synthetic azo dye. No animal inputs. Halal — though some scholars discourage its use due to health concerns, it is not haram.",
    jakimRef: "JAKIM-COL-014",
  },
  {
    name: "Invert Sugar",
    aliases: ["Inverted sugar syrup", "Trimoline"],
    status: "halal",
    category: "Sweetener",
    description: "Mixture of glucose and fructose produced by hydrolysis of sucrose. Plant-derived. No animal inputs. Halal.",
    jakimRef: "JAKIM-SWT-007",
  },
  {
    name: "High Fructose Corn Syrup",
    aliases: ["HFCS", "Glucose-fructose syrup"],
    status: "halal",
    category: "Sweetener",
    description: "Corn starch-derived syrup enzymatically processed to increase fructose content. Plant/enzymatic. Halal when microbial enzyme source is halal.",
    jakimRef: "JAKIM-SWT-008",
  },
];

/** Quick lookup by E-number or common name (case-insensitive) */
export function lookupIngredient(query: string): HalalEntry | undefined {
  const q = query.toLowerCase().trim();
  return HALAL_DICTIONARY.find(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      (e.aliases ?? []).some((a) => a.toLowerCase().includes(q))
  );
}

/** Filter by status */
export function filterByStatus(status: HalalEntry["status"]): HalalEntry[] {
  return HALAL_DICTIONARY.filter((e) => e.status === status);
}

/** Filter by category */
export function filterByCategory(category: string): HalalEntry[] {
  return HALAL_DICTIONARY.filter(
    (e) => e.category.toLowerCase() === category.toLowerCase()
  );
}
